### ISSUE TITLE
Is there any way to listening to system mute/unmute?

### ISSUE THREAD

**Issue by the-eric-kwok** [black-dragon74/ALCPlugFix-Swift#2]
I found that on my laptop with ALC295, `alc-verb 0x1b 0x707 0x1` will make the mute indicator LED on, and `alc-verb 0x1b 0x707 0x0` will make it off. So I'm wondering is there any way to trigger this when mute status changed? 

Before asking this question, I've already tried [this](https://stackoverflow.com/questions/29062592/check-if-system-volume-is-muted) but since I'm not familiar with Swift, I failed. 

Thank you for any reply! :)

**Comment by black-dragon74** [comment]
I'll implement it in a few days. Might be useful for other people like you. Thanks for the idea.

**Comment by black-dragon74** [comment]
@the-eric-kwok Please check and see if the latest release works for you.

**Comment by the-eric-kwok** [comment]
@black-dragon74 It works great!! Thank you so much! That's quick!

**Comment by the-eric-kwok** [comment]
Would you mind adding a feature to detect if device is muted on boot?

**Comment by the-eric-kwok** [comment]
For now I modify your code and add this into func `processOnBootVerbs()`
```swift
        listener.mutePropertyListenerBlock(inNumberAddresses: 0, inAddresses: &listener.muteAddress)
```
It did call `mutePropertyListenerBlock` on start up, but it seems like `audioSourceDidMute` didn't receive the message.

**Comment by black-dragon74** [comment]
I see no purpose in doing that. I get it that you wanna persist the LED state across reboot. But AlcPlugFix has nothing to do with controlling the LEDs. It has to do with sending verbs to codecs whenever an audio property changes. A pre muted source on boot is not a property change.

**Comment by the-eric-kwok** [comment]
I get your point. It's ok to close my PR and issue :P

**Comment by black-dragon74** [comment]
If you wanna do it yourself, `AudioObjectGetPropertyData(defaultDevice, muteAddress, 0, nil, &dataSourceSize, &isMuted) ` is the command that reads the current mute/unmute status into `isMuted` Variable. 

Make sure you call this function after `init` of `Listener`

Regards

**Comment by xCuri0** [comment]
@the-eric-kwok i've fixed mute on boot/wake and also a bug where it would start before `coreaudiod` in my fork

https://github.com/xCuri0/ALCPlugFixMute-Swift/
