### ISSUE TITLE
[Improvements] Better install instructions

### ISSUE THREAD

**Issue by dreamwhite** [black-dragon74/ALCPlugFix-Swift#4]
First of all,
I'd like to thank you for your effort into this project and AppleALC.
I successfully removed `CodecCommander` and every patch earlier applied before testing your project.
Premised that I have enough IQ to understand how to configure your script before proceeding but can you please improve the install instructions?
I admit that it can be difficult for those who'll want to try this project understand them correctly.

e.g. At the moment the only install instructions can be summarized with the following statement "run install.sh" without doing anything. 

There's no explanation which talks about `com.black-dragon74.ALCPlugFix.plist` and `REPLACE_ME` ProgramArgument. What should we do theorically?
In my ignorance I thought that I should put the absolute path of `sample.plist` adapted for my audio codec. Is this wrong despite it's currently working in my laptop?

Many thanks again and have a nice day

**Comment by black-dragon74** [comment]
Well, actually that's all you have to do (provided you have a configuration `PLIST` for your codec ready). You don't even have to touch the launchctl PLIST file. The `REPLACE_ME` is automatically replaced by `install.sh`. It asks you to drag your config file to the terminal window. It also verifies the file to check if it is a proper one. 

I will add the part on how to prepare a plist file to the docs. 

P.S: If you need any clarifications, feel free to ask :) 

Regards

**Comment by dreamwhite** [comment]
Thanks for your reply :) 
I understood the `REPLACE_ME` part (there's literally the following line which does the job):

`$pledit -c "Set ProgramArguments:1 $inputFile" ./com.black-dragon74.ALCPlugFix.plist || abort "Failed to write to launchd plist"`

At this point I have a question: what's the best approach to adopt if we want to run this script on startup?
Basically the script asks for the configuration file. Should I put this file into a folder like my `~/.alcplugfix` folder? 
TYA

**Comment by black-dragon74** [comment]
Not at all. Once you run it and it says **Install successful**, you can forget `install.sh`.

It is only required to install the daemon. Nothing more. 

Regards

**Comment by dreamwhite** [comment]
Alright. I've noticed right now that if I reboot my laptop the service doesn't load on boot and I need to manually start using

`sudo launchctl start /Library/LaunchAgents/com.black-dragon74.ALCPlugFix.plist`

Is this a bug or whatelse? O_O

**Comment by black-dragon74** [comment]
I'd recommend you to `cd` to the release directory, run `install.sh` and it'll set up everything properly. Drag the modified `sample.plist` to the terminal. Don't make any edits. It's all interactive.

Technical explanation, maybe the service is not loaded. Try replacing `start` with `load` in the above command that you're running. Note that you need to `load` only once, it'll be loaded automatically from then on.

You can verify if it's running by `ps -ax | grep AlcPlugFix`

Regards

**Comment by dreamwhite** [comment]
> Technical explanation, maybe the service is not loaded. Try replacing `start` with `load` in the above `launchctl` command that you're running. Note that you need to `load` only once, it'll be loaded automatically from then on.

Alright, I double checked with `launchctl list | grep black` and I see that the service is loaded correctly:

![image](https://user-images.githubusercontent.com/17933708/98103894-00a9fc80-1e96-11eb-8159-6ffb8f5c6bbe.png)

> You can verify if it's running by `ps -ax | grep "AlcPlugFix"`

![image](https://user-images.githubusercontent.com/17933708/98103773-cf313100-1e95-11eb-8ee4-a7b8f5310406.png)

So ALCPlugFix isn't working as expected :'(

I'm on macOS Catalina 10.15.7 (19H2)
Regards

**Comment by dreamwhite** [comment]
So, I've discovered that if the following entries are in `/Library/LaunchAgents/com.black-dragon74.ALCPlugFix.plist`, the service doesn't start on boot:

- `Debug` BOOL
- `StandardErrorPath` STRING
- `StandardOutPath` STRING

I made the following tests:

- boot with vanilla `/Library/LaunchAgents/com.black-dragon74.ALCPlugFix.plist`. Result: **DOES NOT WORK**
- boot with `Debug` set to `0` + `StandardErrorPath` + `StandardOutPath`.  Result: **DOES NOT WORK**
- boot without - `Debug`, `StandardErrorPath`, `StandardOutPath`. Result: **WORKS**

Below the "fixed" service .plist file I'm using:

[com.black-dragon74.ALCPlugFix.plist.zip](https://github.com/black-dragon74/ALCPlugFix-Swift/files/5487547/com.black-dragon74.ALCPlugFix.plist.zip)
 

Please let me know if I have to create a Pull Request or you can push it directly in the master branch.
Regards

**Comment by black-dragon74** [comment]
> service doesn't start on boot

Actually I forgot to publish the release version for this. This bug has been identified and fixed at 165d8c38ded1f147de6be67db3da424092fee017. Please try with the latest [release](https://github.com/black-dragon74/ALCPlugFix-Swift/releases/tag/1.3) and report?

> * boot without - `Debug`, `StandardErrorPath`, `StandardOutPath`. Result: **WORKS**

`Debug` was removed in macOS Mojave so it doesn't matter. The actual cause of this bug was, the script was placing the logs in `var/logs` which is not user writable. Hence the service was failing with error code `78`.

Regards

**Comment by dreamwhite** [comment]
> > service doesn't start on boot
> 
> Actually I forgot to publish the release version for this. This bug has been identified and fixed at [165d8c3](https://github.com/black-dragon74/ALCPlugFix-Swift/commit/165d8c38ded1f147de6be67db3da424092fee017). Please try with the latest [release](https://github.com/black-dragon74/ALCPlugFix-Swift/releases/tag/1.3) and report? The process is same, just run `install.sh`, it will clean up the old install automatically.
> 
> > * boot without - `Debug`, `StandardErrorPath`, `StandardOutPath`. Result: **WORKS**
> 
> `Debug` was removed in macOS Mojave so it doesn't matter. The actual cause of this bug was, the script was placing the logs in `var/logs` which is not user writable. Hence the service was failing with error code `78`.
> 
> Regards

Oh, nice! I'll update this comment and let you know if this works :D

**Comment by black-dragon74** [comment]
I can see no evidence where in you actually ran the `install.sh`. Here’s what you have to do:
- Download the release and extract it
- CD into the extracted dir
- Type `./install.sh`

Post the screenshot of the terminal window.

Regards

**Comment by dreamwhite** [comment]
Sure, here you are the screenshot of the terminal windows after freshly downloading v.1.3 release:

![image](https://user-images.githubusercontent.com/17933708/98138225-2bf71080-1ec3-11eb-9474-b1010d28cc68.png)

I'll reboot right now and let you know if headphones works
