### ISSUE TITLE
ALC256 

### ISSUE THREAD

**Issue by abdllhcrk** [black-dragon74/ALCPlugFix-Swift#5]
Hello, can you help me to add New codec support for ALC256 ? I tried everything but i really don't know what to do. If you want, I can send my Codec Dump file.

**Comment by black-dragon74** [comment]
What do you mean by "Adding codec support"? 

AppleALC already has your codec support. Check https://github.com/acidanthera/AppleALC/wiki/Supported-codecs

Also, please don't open issues for any problems not related to `AlcPlugFix-Swift`. Use the forums for that. 

Regards
