### ISSUE TITLE
How can I make config file for my laptop

### ISSUE THREAD

**Issue by nikhil19rathore99** [black-dragon74/ALCPlugFix-Swift#7]
Hello,
I have Asus X556UQK laptop
intel i5-7200U, Kabylake
ALC id - 27 everything's works but sometimes audio crackles and (currently I use jack fix by Goodwin) which will not works plug/unplug jack fix properly
OS : 11.0.1 BigSurr
BootLoader: Clover 5127
all kext are updated to last version
THANKS

**Comment by black-dragon74** [comment]
You update sample.plist with the commands you need to fix the crackling sound. Also, this is not a support forum. Open issues only when it is related to the project itself. 

Regards
