### ISSUE TITLE
[AppleALC 1.5.5] Provider ALCUserClientProvider not available!

### ISSUE THREAD

**Issue by dreamwhite** [black-dragon74/ALCPlugFix-Swift#8]
Good evening,
I've updated to AppleALC 1.5.5 from 1.5.4 and your script stopped working. Maybe it needs an update?
Thanks ^^

**Comment by black-dragon74** [comment]
No it doesn't. Take a look at `Readme.MD`. Specifically **Note** under **Features**.

**Comment by dreamwhite** [comment]
> No it doesn't. Take a look at `Readme.MD`. Specifically **Note** under **Installing**.

Thanks for your reply. I tried adding `alc-verbs=1` boot-arg as suggested, but I'm still experiencing the same issue with ALCPlugFix-Swift 1.4 :/  

Below a screenshot of `nvram -p` and `kmutil showloaded | grep AppleALC`

![image](https://user-images.githubusercontent.com/17933708/101390555-4dcd2400-38c3-11eb-9bdf-6efca728c632.png)

**Comment by black-dragon74** [comment]
Could you attach an copy of your IOREG please?

**Comment by black-dragon74** [comment]
Sorry. Just noticed. There's a typo in the README, you need to use `alcverbs=1` if using boot-args and `alc-verbs` if you prefer the property method. 

Sorry. Could you try again with proper boot-arg?

**Comment by dreamwhite** [comment]
> Could you attach an copy of your IOREG please?

Sure I'll attach a 3.0.2 IORegistryExplorer dump^^ 
I've just removed `alc-verbs=1` boot-arg and added the property `alc-verb` on DeviceProperties in my config.plist, but the issue is still here...

[dreamBookPro.ioreg.zip](https://github.com/black-dragon74/ALCPlugFix-Swift/files/5654573/dreamBookPro.ioreg.zip)

**Comment by dreamwhite** [comment]
> Sorry. Just noticed. There's a typo in the README, you need to use `alcverbs=1` if using boot-args and `alc-verbs` if you prefer the property method.
> 
> Could you try again with proper boot-arg?

Oh, I'll test right now and let you know .-.

**Comment by black-dragon74** [comment]
> > Could you attach an copy of your IOREG please?
> 
> 
> 
> Sure I'll attach a 3.0.2 IORegistryExplorer dump^^ 
> 
> I've just removed `alc-verbs=1` boot-arg and added the property `alc-verb` on DeviceProperties in my config.plist, but the issue is still here...
> 
> 
> 
> [dreamBookPro.ioreg.zip](https://github.com/black-dragon74/ALCPlugFix-Swift/files/5654573/dreamBookPro.ioreg.zip)
> 
> 

It's `alc-verbs` in properties and `alcverbs=1` as boot-arg. You're missing the `s`.

**Comment by black-dragon74** [comment]
Nope. The typo was in my `README.md`. Glad it's fixed for you.

**Comment by dreamwhite** [comment]
Wait, AppleALC v1.5.5 page has the following statement:

Added a requirement to inject `alc-verbs` or use `alc-verbs=1` argument for custom verbs.

The boot-arg shouldn't have the `-`

**Comment by black-dragon74** [comment]
Oh the changelog. Feel free to do so.
